[package]
name = "caylang-io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwalk = "0.8.1"
tempdir = "0.3.7"
dir-diff = "0.3.2"
fs_extra = "1.3.0"
